// Code generated by HandlersGen. DO NOT EDIT.
// Source: api.go

package main

import (
	"bytes"
	"encoding/binary"
	"net/http"
)

func (srv *MyApi) profile(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
}
func (srv *MyApi) create(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
}
func (srv *OtherApi) create(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
}
